#!/bin/bash

# Script for uploading to areas in the Genestack
# S3 buckets for use in the uploadtogenestack app

# Author: Michael Grace <mg38@sanger.ac.uk>

# Usage: gs-upload {-qc} PROJECT_NAME LIST_OF_FILES...

if [[ $1 == "-h" || $# -lt 2 || ($1 == "-qc" && $# -lt 3) ]]; then
    echo "usage: gs-upload [-qc] PROJECT-NAME FILE..."
    exit 1
fi

function red_text {
    echo -e "\e[1m\e[31m${@}\e[0m"
}

function yellow_text {
    echo -e "\e[1m\e[33m${@}\e[0m"
}

function green_text {
    echo -e "\e[1m\e[32m${@}\e[0m"
}

function blue_text {
    echo -e "\e[1m\e[34m${@}\e[0m"
}

function private_bucket {
    if [[ -f "${HOME}/gs-private" ]]; then
        ~/gs-private > /dev/null &
    else
        red_text "can't make S3 buckets private"
    fi
    exit $1
}

blue_text "Genestack Uploader"

if [[ $1 == "-qc" ]]; then
    offset=1
    bucket="genestackuploadtest"
    instance="Genestack QC"
else
    offset=0
    bucket="genestackupload"
    instance="Main Genestack"
fi

if [[ -f "${HOME}/gs-public" ]]; then
    # WARNING: Make sure we make the buckets private again after
    ~/gs-public > /dev/null
else
    yellow_text "can't make the S3 policy public - may not be able to upload"
fi

# Let's see if the project already exists
project_loc=$((1 + $offset))
new_project=${!project_loc}
projects=$(s3cmd ls s3://${bucket}/projects/ | grep DIR | cut -d '/' -f 5 | grep ${new_project})

if [[ $projects != "" ]]; then
    red_text "already found project name ${new_project}"
    private_bucket 1
fi

# If the project doesn't exist, then we'll happily upload stuff
file_start=$((2 + $offset))
files=${@:file_start}

s3res=$(s3cmd put ${files} s3://${bucket}/projects/${new_project}/ 2>&1)

if [[ s3res == WARNING* ]]; then
    red_text "couldn't upload to S3"
    red_text "$s3res"
    private_bucket 1
fi

green_text "Upload Complete"
echo "The files can be referenced in the Genestack uploader app for the ${instance} instance like this:"
s3cmd ls s3://${bucket}/projects/${new_project}/ | cut -d '/' -f 4-
private_bucket 0